---
title: "Calibration of Urban Planning and Transport Health Assessment Toolkit"
output:
   #word_document: default
   github_document
   #pdf_document:
   #  number_sections: yes
   #html_document:
   #     toc: true
   #     toc_float: true
   #     number_sections: true
   #     theme: flatly
bibliography: ../ATF.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
library(dplyr)
knitr::opts_chunk$set(
  echo = FALSE,
  out.width = "100%",
  collapse = TRUE,
  comment = "#>"
)
if (!file.exists ("ATF.bib")) { # delete file to auto-update
    refs <- RefManageR::ReadZotero(group = "418217",
                    .params = list(collection = "TJEQMXJR", limit = 100))
    RefManageR::WriteBib(refs, "ATF.bib")
}
```


# Introduction

Calibration of UPTHAT (the Urban Planning and Transport Health Assessment
Toolkit) relies primarily on new high performace software
[@padgham_dodgr:_2019] for analysing dynamic movement through urban areas.

This manuscript details procedures developed for calibrating UPTHAT estimates
of both pedestrian and cyclist densities along individual street segments
against empirical data from New York City, USA.

# Methods

## Data Sources

UPTHAT is based out of principle on entirely open data sets, primarily on data
from Open Street Map and "worldpop" (www.worldpop.org). The latter data enable
estimates of population flows to be made in absolute terms, given aggregate
data on proportions and typical frequencies of trips.

Additional data on pedestrian densities was obtained from New York City
Government [pedestrian count
data](https://www1.nyc.gov/html/dot/html/about/datafeeds.shtml#Pedestrians),
collected bi-annually at 114 stations throughout the city, and on cyclist
densities from data provided by the city's "citibike" public hire bicycle
system. Additional data on subway usage was obtained from the city's
[Metropolitan Transit
Authority](http://web.mta.info/nyct/facts/ridership/ridership_sub_annual.htm),
with data on locations obtained through the city's [open data
portal](https://data.cityofnewyork.us/Transportation/Subway-Stations/arq3-7z49).

### The Street Network

Both the street network used to route pedestrian journeys, and the structure,
nature, and location of buildings serving as origins and/or destinations of
those journeys were obtained from Open Street Map, accessed via the R package,
`osmdata` [@padgham_osmdata_2017]. The network consisted of 813,402 street
segments, representing a total 30,226 km. These segments are simply those used
to represent Open Street Map, such that a single linear length of way may be
represented by several points, and several corresponding edges in our internal
representation. We then used the `dodgr` software [@padgham_dodgr:_2019] to
"contract" this network down to segments between junctions points only,
reducing it to 407,840 segments.

Each of these 407,840 segments had an associated length, along with further
detail as contained in the Open Street Map data, including the type of way
(with such values as "cycleway", "footway", "pedestrian", or "steps"). These
types were used to weight the distances to reflect typical pedestrian
preferences [@luxen_real-time_2011], to enable pedestrian routes to be
accurately calculated. These weighting schemes act to extend the effective
length of ways unsuitable for pedestrians, for example, by multiplying actual
lengths of major vehicular roads by some factor representative of the
associated pedestrian discomfort in comparison to quiet, pedestrian-only ways.
All weighting factors are greater than one, so that the most
pedestrian-friendly ways retain their original distances, while ways less
suitable for pedestrian travel have weighted lengths greater than their actual
lengths. Routing is then conducted using these weighted lengths, and so routes
reflect those that would be typically chosen by pedestrians. Rather than
distance-based routing, we used time-based routing, which operates on a similar
principle, but introduces several categories of additional time-based
penalties, notably for waiting at traffic lights, or for waiting to cross busy,
multi-lane roads (where such crossing is permitted). All routing was
implemented using the authors' own `dodgr` software [@padgham_dodgr:_2019].

### Trip categories

Open Street Map includes not only streets, but also buildings with optional yet
frequently extensive descriptions of categories, purpose, sizes, and other
properties. These building descriptions enable Open Street Map to be used to
identify likely locations of trip origins and destinations according to trip
purpose. In particular, we divided building categories into the five main
groups of transportation, sustenance, entertainment, education, and healthcare,
each by grouping the Open Street Map tags given in Appendix 1. Transportation
notably included all parking facilities, both for bicycles and automobiles.

For each of these categories, we estimated local intensities of the respective
activities by attributing all buildings to the nearest street network junction,
and aggregating numbers at each junction. These numbers provided estimates of
likely numbers of people originating from or coming to that point for the
respective activities.

Beyond these Open Street Map-based estimates, we also used Worldpop data to
ascribe aggregate residential densities to each street junction, and subway
counts to represent journeys to or from entrances and exits of the New York MTA
subway system. A final category was based on the betweenness centrality of the
entire street network. Centrality is known to be a strong determinant of travel
behaviour, with more central points, or street segments, correlated with higher
densities of movements towards or away from those points or segments. A final
categorical trip purpose considered in our analyses below is thus,
"centrality".

Extraction and processing of these data enabled analyses of the following eight
trip categories, serving as types of journey origins or destinations:

n | category
--- | ---
1 | subway
2 | centrality
3 | residential
4 | transportation
5 | sustenance
6 | entertainment
7 | education
8 | healthcare

## Modelling Pedestrian Flows

We modelled pedestrian flows throughout the entirety of New York City, USA, in
order to calibrate our models against the empirical data from the 114
pedestrian count stations. Models were constructed using the
[`dodgr`](https://github.com/atfutures/dodgr) software package for large-scale
routing through street networks, by assembling an array of "flow layers"
representing pedestrian flows between the distinct categories of origin and
destination points described above.

Flow layers were generated in two primary ways: either by dispersing from
a given set of origin points according to specified densities, or through
routing flows between specific sets of origin and destination points, with
densities calculated by a doubly-constrained spatial interaction model, with
exponential form used throughout [@wilson_boltzmann_2008]. We refer to these
two methods of calculating flow layers as "flow dispersal" and "flow
aggregation", and illustrate both in the following sub-sections.

Each of the flow layers described below was initially independently calibrated
against the observed pedestrian flows, by extracting flow values along the
network segments corresponding to each pedestrian count location, and
minimising the standardised error of a linear regression model. We applied
weighted regression, weighting each observed value of $n$ pedestrian counts by
some factor, $0\ge\lambda\le1$, as $n^\lambda$, where $\lambda = 0$ yields an
unweighted regression which minimises the overall *relative* error, while
values of $\lambda\rightarrow1$ minimise the absolute error, through weighting
the contributions of errors on observations with high pedestrian counts in
proportion to those counts. Values of $\lambda$ were automatically selected as
those giving the lowest overall model error. Values of `lambda` were
automatically selected for each regression as that value minimising the
resultant model error, with all correlation strengths reported throughout the
following (as $R^2$ values) corresponding to the resultant values of $\lambda$,
which are also stated for all reported correlations.

### Spatial Interaction Models

We generated flows along the shortest paths between all origins, $i$, and
destinations, $j$, according to exponential spatial interaction models
[@wilson_boltzmann_2008] of the form,
\begin{equation}
    SI_{ij} (d_{ij}) = \frac{n_in_j}{\sum_j n_j exp (-d_{ij} / k)} exp (-d_{ij} / k),
\end{equation}
where $d_{ij}$ denotes the distance between the points $i$ and $j$. The
denominator ensured that our models were singly-constrained to unit sums for
each origin, $i$, over densities at destinations, $j$. The above form gives the
expected flow, in direct units of $n_i$, along the path between the points $i$
and $j$.

We further modified these standard spatial interaction models to accommodate
a possibility that people may tend to walk different average or typical
differences in different locations dependent on levels of overall pedestrian
activity in those locations. In particular, we hypothesised that people may be
more likely to walk further in more prominent centres than in more peripheral
locations of lower aggregate pedestrian activity. We thus introduced an
additional parameter in the above model, which also retained the possibility
that people may in fact walk shorter distances in more prominent centres. This
parameter, $\alpha$, simply served to scale observed exponential decay
coefficients according to the sizes of origins, $n_i$, giving flows between
origins, $i$, and destinations, $j$, according to sizes or origins, $n_i$,
rescaled to relative values of $n_i^\prime = n_i/max_j (n_j)$, as,
\begin{equation}
    F_{ij} (d_{ij}; k, \alpha) = \frac{n_in_j}
    {\sum_j n_j exp (-d_{ij} / k ^ {1 + \alpha n_i^\prime})}
    exp (-d_{ij} / k ^ {1 + \alpha n_i^\prime}).
\end{equation}


### Flow Layers

Our models comprised a variety of flow layers, each of which was generated by
applying the spatial interaction models described above between a specified set
of origin points, taken from the eight categories given above. Each flow layer
was obtained through calculating shortest paths between each origin point and
destination point in the network, and aggregating the corresponding values of
$F_{ij} (d_{ij})$ along each segment of each shortest path. Layers were also
calculated describing undirected dispersal throughout the entire network from
a set of origin points. These dispersal models are equivalent to a set of
destination points comprising the entire network, with unit destination sizes,
$n_j = 1\forall j$.

We used the 8 categories of points shown in Table 1, below, to generate
$8\times7 = 56$ flow layers between all pairwise combinations of origins and
destinations. An additional 8 layers described dispersal from each of origin
points defined by each of the categories, for a final total of 64 flow layers.


### Statitstical Models

The 64 pairwise combinations of origin and destination categories represents 64
potential independent variables in a statistical model. Our final model
incorporated only a small fraction of this total number, through applying
a step-wise variable addition procedure. We first independently correlated all
layers with the observed counts, independently adjusting the single model
parameters of $k$ for each layer in order to minimise model error, holding the
second parameter at $\alpha = 0$ throughout. The minimal-error layer was then
selected, and the value of $\alpha$ adjusted to further minimise the model error.

The next layer-selection step incorporated that layer, and again independently
adjusted values of $k$ for each layer to identify the layer giving the lowest
error as part of a multiple-linear regression model including the previously
selected layer. Having selected the second layer, the corresponding value of
$\alpha$ was then adjusted to further minimise the overall model error. The
third layer was then selected through again adjusting values of $k$ for each
remaining layer, and identifying the layer yielding the lowest error in a model
including the previous two layers. Having selected this layer by adjusting $k$
while holding $\alpha = 0$, the overall error was again further minimised by
adjusting the value of $\alpha$ for this layer. This procedure was repeated as
long as the contribution of each new layer to the model was statistically
significant, generally resulting in the selection of only a handful of the 64
layers.


# References
